openapi: 3.2.0
info:
  title: Datahub Cpm Parser Store API
  description: OpenAir Datahub acts as a central data repository for all functions, which affect the efficient functioning of an airport. Data can be ingested from various sources via standardized interfaces. The way of getting data out of it is similar; there are standardized REST and MQTT interfaces to fetch the data. The data structure is based on industry standards such as IATA's AIDM and ACI's ACRIS combined with decades of Vanderlande Logistics industry knowledge.
  contact:
    name: Vanderlande Logistics GmbH
    url: https://www.vanderlande.com
    email: info.digital@vanderlande-logistics.com
  license:
    name: Property of Vanderlande Logistics GmbH
  version: 6.6.0
tags:
- name: Cpm Parser Store
  externalDocs:
    description: The cpm store contains methods to access and insert CPM's
paths:
  /parser/cpm:
    get:
      tags:
      - Cpm Parser Store
      summary: Get parsed CPM's
      description: Return empty result if there are no CPM. If no query parameter is set the search will be reduced to the last 24 hours. If no maxResult is set a maximum of 1000 records will be returned.
      operationId: getCpms
      parameters:
      - name: from
        in: query
        description: The start point of the interval in UTC. e.g. 2020-01-31T12:30:00.000Z. If used the from and the to parameter has to be set.
        required: false
        schema:
          type: string
      - name: to
        in: query
        description: The end point of the interval in UTC. e.g. 2020-01-31T12:30:00.000Z. If used the from and the to parameter has to be set.
        required: false
        schema:
          type: string
      - name: carrier
        in: query
        description: IATA 2-digit code of the operating carrier.
        required: false
        schema:
          type: string
      - name: flight-number
        in: query
        description: The numeric flight number of operating airline.
        required: false
        schema:
          type: string
      - name: origin-date
        in: query
        description: The day of operation, i.e. local day of schedule off-block time in UTC at first departure airport of flight. e.g. 2020-01-31T12:30:00.000Z.
        required: false
        schema:
          type: string
      - name: max-results
        in: query
        description: The maximum number of results.
        required: false
        schema:
          type: integer
          format: int32
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Cpm'
        '400':
          description: Bad Request
          content:
            '*/*':
              schema:
                oneOf:
                - type: object
                  additionalProperties:
                    type: object
                - type: object
                  additionalProperties:
                    type: string
      security:
      - aviationdatahub:
        - ADH.FL.R
    post:
      tags:
      - Cpm Parser Store
      summary: Post a CPM
      description: Posting a IATA message CPM - container pallet message.
      operationId: parserCpm
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CpmRawMessage'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
        '400':
          description: Bad Request
          content:
            '*/*':
              schema:
                oneOf:
                - type: object
                  additionalProperties:
                    type: object
                - type: object
                  additionalProperties:
                    type: string
  /parser/cpm/{id}:
    get:
      tags:
      - Cpm Parser Store
      summary: This endopint queries CPMs that have been posted to ADH
      operationId: getCpmById
      parameters:
      - name: id
        in: path
        description: UUID that was provided upon creation.
        required: true
        schema:
          type: string
      responses:
        '200':
          description: CPM message was successfully retrieved.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cpm'
        '400':
          description: Bad Request
          content:
            '*/*':
              schema:
                oneOf:
                - type: object
                  additionalProperties:
                    type: object
                - type: object
                  additionalProperties:
                    type: string
        '404':
          description: CPM message not found.
          content:
            application/json:
              example:
                id: 78ce2036-cd5f-11ed-afa1-0242ac120002
      security:
      - aviationdatahub:
        - ADH.FL.R
components:
  schemas:
    FlightDataCpm:
      type: object
      properties:
        flight-designator:
          type: string
          description: Airline and Flight Number
          example: UA423
        origin-date:
          type: string
          description: Scheduled date for departure date. Format is YYYY-MM-DD.
          example: '2023-03-30'
        carrier:
          type: string
          description: The flight carrier
          example: UA
        flight-number:
          type: string
          description: The flight number
          example: 423
        operational-suffix:
          type: string
          example: A
        origin-iata-code:
          type: string
          description: Origin Airport IATA code
          example: SIN
        destination-iata-code:
          type: string
          description: Destination Airport IATA code
          example: DXB
        class-of-travel:
          type: string
          description: Y, F, etc.
          example: F
        sequence-number:
          type: integer
          format: int32
          description: Sequence Flight Number
          example: 1
        aircraft-registration:
          type: string
          description: Registration of aircraft composed of 2-10 printable characters
          example: A7BBG
    Cpm:
      type: object
      properties:
        ulds:
          type: array
          items:
            $ref: '#/components/schemas/Uld'
        bulk:
          type: array
          items:
            type: string
        inbound-flight:
          $ref: '#/components/schemas/FlightDataCpm'
        supplementary-info:
          type: array
          items:
            type: string
        additional-text:
          type: array
          items:
            type: string
    Uld:
      type: object
      properties:
        unknownFields:
          type: array
          items:
            type: string
        load-position:
          type: string
          description: ULD bay designation consisting of 1-3 alpha-numeric characters
          example: 11L
        tag:
          type: string
          description: ULD type code, serial number and airline designator
          example: AKE06476AF
        container-subtype:
          type: string
          description: Type of container
          example: AKE
        destination-iata-code:
          type: string
          description: Destination airport IATA code
          example: SIN
        weight:
          type: string
          description: Weight of ULD
          example: 290
        load-category-code:
          type: string
          description: C = cargo, B = baggage, D = crew baggage, E = equipment, F = first class/priority, H = onward ULD, M = mail, N = no ULD at position
          example: C
        all-load-category-codes:
          type: array
          description: All load category codes used (together with additional information, if existent)
          example: CA
          items:
            type: string
        volume-code:
          type: string
          description: Additional category codes used together with the load category
          example: CA
        load-remarks:
          type: array
          description: Special load remarks
          example: '[CRT/0, AVI]'
          items:
            type: string
      required:
      - load-position
    CpmRawMessage:
      type: object
      description: A CPM encapsulated in a JSON structure.
      properties:
        message:
          type: string
          description: Content of a CPM
          example: 'CPM

            AB1234/12.A7BBG

            -11L/QKE57447QR/CDE/290/C.PLD.RMD'
        pipeline:
          type: string
        correlation-id:
          type: string
          description: The global id which identifies this object across multiple applications. If no correlation id is provided, ADH will generate one.
          example: 3fa85f64-5717-4562-b3fc-2c963f66afa6
      required:
      - message
